# .github/workflows/export-file.yml
name: Export File

on:
  workflow_call:
    outputs:
      data_content:
        description: "Content of data.txt"
        value: ${{ jobs.export.outputs.data }}

jobs:
  export:
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.get_content.outputs.result }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get content
        id: get_content
        run: |
          if [ -f data.txt ]; then
            echo "result=$(cat data.txt)" >> $GITHUB_OUTPUT
          else
            echo "result=No data" >> $GITHUB_OUTPUT
