name: "infra preview & deploy"

on: 
    push:
        branches:
            - main
        paths:
            - '10_infra/**'
            - '.github/workflows/**'
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

env:
    AWS_REGION: "ap-northeast-1"
    TF_VERSION: "1.1.7"

defaults:
    run:
        shell: bash
        working-directory: "10_infra/"

jobs:
    preview:
        name: "Preview"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with: 
                terraform_version: ${{ env.TF_VERSION }}
                terraform_wrapper: false
            - name: Terraform Format
              run: |
                terraform fmt -check
            - name: AWS Configure   
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: ${{ env.AWS_REGION }}
                role-to-assume: ${{ secrets.AWS_IAM_ROLO_ARN }}
            - name: Terraform Init
              run: |
                terraform init -no-colorｓ
