name: Sample                        
on: [push,workflow_dispatch]                              

jobs:                                  
  sample:                               
    runs-on: ubuntu-latest              
    steps:                              
      - run: echo "Hello GitHub Action"

  checkout:
    needs: [sample]                 # sampleのジョブが終了したら、このジョブが動く
    runs-on: ubuntu-latest              
    steps:                              
      - uses: actions/checkout@v3

  start:
    needs: [sample]                 # sampleのジョブが終了したら、このジョブが動く
    runs-on: ubuntu-latest              
    steps:                              
      - run: echo "Start Test"

  test:
    needs: [checkout, start]        # sampleのジョブが終了したら、このジョブが動く
    runs-on: ubuntu-latest              
    steps:                              
      - run: echo "Start Test"
                                 
  sendChat:
    # needs: []                     # needsを設定していないため、ワークフロー開始時に「sample」と同時に動く
    runs-on: ubuntu-latest              
    steps:                              
      - run: echo datetime
