name: Sample                        
on: [push,workflow_dispatch]                              

jobs:                                  
  sample_1:                               
    runs-on: ubuntu-latest              
    steps:                              
      - run: echo "Hello GitHub Action"

  checkout_2 :
    needs: [sample_1]                 # sampleのジョブが終了したら、このジョブが動く
    runs-on: ubuntu-latest              
    steps:                              
      - uses: actions/checkout@v3

  start_2 :
    needs: [sample_1]                 # sampleのジョブが終了したら、このジョブが動く
    runs-on: ubuntu-latest              
    steps:                              
      - run: echo "Start Test"

  test_3 :
    needs: [checkout_2, start_2]      # sampleのジョブが終了したら、このジョブが動く
    runs-on: ubuntu-latest              
    steps:                              
      - run: echo "Start Test"
                                 
  sendChat_1 :
    # needs: []                       # needsを設定していないため、ワークフロー開始時に「sample」と同時に動く
    runs-on: ubuntu-latest              
    steps:                              
      - run: echo datetime
