name: Step Data Transfer ENV  
on: [workflow_dispatch]                              

jobs:                                  
  step_data_transfer_env:
    runs-on: ubuntu-latest
    steps:
      - id : send_env
        run: echo "result=Hello GitHubAction Env" >> "${GITHUB_ENV}"
      - id : receive_env
        run: echo "${RESULT}"